blank_issues_enabled: true
contact_links:
  - name: Questions & ideas
    url: https://github.com/DynamycSound/window_control_tool/discussions
    about: For general questions, use Discussions instead of issues.
